# Generated by Django 3.0 on 2019-12-17 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Задача', max_length=30)),
                ('timer', models.IntegerField(default=0)),
                ('color', models.CharField(default='0, 0, 0, 0', max_length=30)),
                ('is_counting', models.IntegerField(default=0)),
                ('partnumber', models.IntegerField(default=0)),
                ('to_show', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_site', models.URLField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertask_id', models.IntegerField(default=0)),
                ('date_start', models.DateField()),
                ('time_start', models.TimeField()),
                ('datetime_start', models.DateTimeField(default='0001-01-01 00:00:00')),
                ('date_stop', models.DateField(default='0001-01-01')),
                ('time_stop', models.TimeField(default='00:00:00')),
                ('datetime_stop', models.DateTimeField(default='0001-01-01 00:00:00')),
                ('comment', models.CharField(max_length=200)),
                ('time_length', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
