# Generated by Django 2.2.4 on 2019-10-02 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Задача', max_length=30)),
                ('timer', models.IntegerField(default=0)),
                ('color', models.CharField(default='0, 0, 0, 0', max_length=30)),
                ('is_counting', models.IntegerField(default=0)),
                ('partnumber', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete='Do_Nothing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_site', models.URLField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete='Do_Nothing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField()),
                ('time_stop', models.DateTimeField()),
                ('comment', models.CharField(max_length=200)),
                ('time_length', models.IntegerField(default=0)),
                ('UserTask', models.ForeignKey(on_delete='Do_Nothing', to='basic_app.UserTask')),
                ('user', models.ForeignKey(on_delete='Do_Nothing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
