# Generated by Django 2.2.4 on 2019-10-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parttask',
            name='time_stop',
            field=models.DateTimeField(null=True),
        ),
    ]
