# Generated by Django 2.2.4 on 2019-10-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20191002_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parttask',
            name='time_stop',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
