# Generated by Django 4.1.5 on 2025-12-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_usertask_comment_usertask_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
