# Generated by Django 4.1.5 on 2026-03-22 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_kanban_builtins(apps, schema_editor):
    User = apps.get_model("auth", "User")
    KanbanColumnDefinition = apps.get_model("basic_app", "KanbanColumnDefinition")
    seeds = (
        ("TODO", "To Do", 0, True),
        ("IN_PROGRESS", "In Progress", 1, True),
        ("COMPLETED", "Done", 2, True),
        ("CANCELLED", "Cancelled", 9999, True),
    )
    for user in User.objects.all():
        for key, label, sort_order, is_builtin in seeds:
            KanbanColumnDefinition.objects.get_or_create(
                user=user,
                key=key,
                defaults={
                    "label": label,
                    "sort_order": sort_order,
                    "is_builtin": is_builtin,
                },
            )


def unseed_kanban_builtins(apps, schema_editor):
    KanbanColumnDefinition = apps.get_model("basic_app", "KanbanColumnDefinition")
    KanbanColumnDefinition.objects.filter(is_builtin=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_app', '0003_usertask_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='status',
            field=models.CharField(default='TODO', max_length=64),
        ),
        migrations.CreateModel(
            name='KanbanColumnDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField()),
                ('is_builtin', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_columns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.AddIndex(
            model_name='kanbancolumndefinition',
            index=models.Index(fields=['user', 'sort_order'], name='basic_app_k_user_id_12a16d_idx'),
        ),
        migrations.AddConstraint(
            model_name='kanbancolumndefinition',
            constraint=models.UniqueConstraint(fields=('user', 'key'), name='uniq_kanban_column_user_key'),
        ),
        migrations.RunPython(seed_kanban_builtins, unseed_kanban_builtins),
    ]
