# Generated by Django 2.2.4 on 2019-10-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20191003_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parttask',
            name='time_stop',
            field=models.DateTimeField(default='0001-01-01 00:00:00'),
        ),
    ]
