# Generated by Django 2.2 on 2019-07-08 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20170307_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user',
            field=models.OneToOneField(on_delete='Do_Nothing', to=settings.AUTH_USER_MODEL),
        ),
    ]
