# Generated by Django 2.2.4 on 2019-10-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20191003_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parttask',
            name='UserTask',
        ),
        migrations.AlterField(
            model_name='parttask',
            name='id',
            field=models.OneToOneField(on_delete='Do_Nothing', primary_key=True, serialize=False, to='basic_app.UserTask'),
        ),
    ]
