# Generated by Django 2.2 on 2019-07-11 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_app', '0006_auto_20190708_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Задача', max_length=30)),
                ('timer', models.TimeField(default='00:00:00')),
                ('color', models.CharField(default='0, 0, 0, 0', max_length=30)),
                ('user', models.OneToOneField(on_delete='Do_Nothing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
