# Generated by Django 4.1.5 on 2026-03-24 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_app', '0006_update_builtin_kanban_column_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='kanbancolumndefinition',
            name='uniq_kanban_column_user_key',
        ),
        migrations.AddField(
            model_name='usertask',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kanbancolumndefinition',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kanban_columns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий'), (4, 'Срочный')], default=2),
        ),
        migrations.AddField(
            model_name='kanbancolumndefinition',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kanban_columns', to='basic_app.taskteam'),
        ),
        migrations.AddField(
            model_name='usertask',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='basic_app.taskteam'),
        ),
        migrations.CreateModel(
            name='TaskTeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='basic_app.taskteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='kanbancolumndefinition',
            index=models.Index(fields=['team', 'sort_order'], name='basic_app_k_team_id_87e751_idx'),
        ),
        migrations.AddIndex(
            model_name='usertask',
            index=models.Index(fields=['team', 'status'], name='basic_app_u_team_id_8d4750_idx'),
        ),
        migrations.AddIndex(
            model_name='usertask',
            index=models.Index(fields=['team', 'assignee'], name='basic_app_u_team_id_7d29f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='kanbancolumndefinition',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(('user__isnull', False), ('team__isnull', True)),
                    models.Q(('user__isnull', True), ('team__isnull', False)),
                    _connector='OR',
                ),
                name='kanban_column_user_xor_team',
            ),
        ),
        migrations.AddConstraint(
            model_name='kanbancolumndefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'key'), name='uniq_kanban_column_user_key'),
        ),
        migrations.AddConstraint(
            model_name='kanbancolumndefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', False)), fields=('team', 'key'), name='uniq_kanban_column_team_key'),
        ),
        migrations.AddIndex(
            model_name='taskteammembership',
            index=models.Index(fields=['team', 'user'], name='basic_app_t_team_id_178da3_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskteammembership',
            constraint=models.UniqueConstraint(fields=('team', 'user'), name='uniq_task_team_membership_team_user'),
        ),
    ]
