# Generated by Django 2.2 on 2019-07-11 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_usertask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='user',
            field=models.ForeignKey(on_delete='Do_Nothing', to=settings.AUTH_USER_MODEL),
        ),
    ]
