# Generated by Django 2.2.4 on 2019-10-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_auto_20191005_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parttask',
            name='id',
            field=models.ForeignKey(on_delete='Do_Nothing', primary_key=True, serialize=False, to='basic_app.UserTask'),
        ),
    ]
