# Generated by Django 2.2 on 2019-07-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_auto_20190711_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='timer',
            field=models.CharField(default='00:00:00', max_length=10),
        ),
    ]
