# Generated by Django 2.2.4 on 2019-10-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0009_auto_20191005_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttask',
            name='usertask_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parttask',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
