# Generated by Django 2.2 on 2019-07-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0009_auto_20190712_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='timer',
            field=models.IntegerField(default=0),
        ),
    ]
