# Generated by Django 2.2.4 on 2019-10-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0010_auto_20191009_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttask',
            name='date_start',
            field=models.DateField(default='0001-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parttask',
            name='date_stop',
            field=models.DateField(default='0001-01-01'),
        ),
        migrations.AlterField(
            model_name='parttask',
            name='time_start',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='parttask',
            name='time_stop',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
