# Generated by Django 2.2.4 on 2019-10-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0011_auto_20191012_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttask',
            name='datetime_start',
            field=models.DateTimeField(default='0001-01-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='parttask',
            name='datetime_stop',
            field=models.DateTimeField(default='0001-01-01 00:00:00'),
        ),
    ]
