# Generated by Django 2.2.4 on 2019-11-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0012_auto_20191012_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='to_show',
            field=models.IntegerField(default=1),
        ),
    ]
